"""
Complete disease information database for all 38 PlantVillage classes.
Every disease has: name, crop, severity_default, description, symptoms,
treatment, prevention, organic_treatment, affected_season.
"""

DISEASES = {
    "apple_scab": {
        "name": "Apple Scab",
        "crop": "Apple",
        "severity_default": "Moderate",
        "emoji": "🍎",
        "color": "#e74c3c",
        "description": "Apple Scab is one of the most serious diseases of apple trees worldwide, caused by the fungus Venturia inaequalis. It thrives in cool, moist spring weather.",
        "symptoms": ["Olive-green to brown spots on leaves", "Dark, scabby lesions on fruit surface", "Distorted leaves that drop early", "Cracked, corky fruit skin"],
        "treatment": ["Apply fungicide (Captan, Mancozeb, or Myclobutanil) every 7–14 days during wet weather", "Remove and destroy infected leaves and fruit", "Prune to improve air circulation", "Apply dormant oil spray before buds open"],
        "prevention": ["Plant scab-resistant apple varieties", "Rake and destroy fallen leaves in autumn", "Avoid overhead irrigation", "Ensure good air circulation through pruning"],
        "organic_treatment": ["Neem oil spray (diluted 1:32)", "Lime sulfur spray during dormant season", "Baking soda solution (1 tbsp per quart of water)"],
        "affected_season": "Spring (wet/cool conditions)",
    },
    "apple_black_rot": {
        "name": "Apple Black Rot",
        "crop": "Apple",
        "severity_default": "Severe",
        "emoji": "🍎",
        "color": "#2c3e50",
        "description": "Black rot is caused by the fungus Botryosphaeria obtusa and can affect fruit, leaves, and limbs. It is one of the more serious apple diseases in warm, humid regions.",
        "symptoms": ["Purple spots on leaves that expand to 'frog-eye' lesions", "Black, rotting fruit that shrivels into mummies", "Reddish-brown cankers on branches"],
        "treatment": ["Remove mummified fruit from trees and ground", "Prune out dead and cankered branches (6 inches below visible infection)", "Apply fungicide (Captan or copper-based) at regular intervals"],
        "prevention": ["Remove all dead wood from trees annually", "Avoid leaving fruit mummies on the tree", "Maintain tree vigor through proper fertilization"],
        "organic_treatment": ["Copper sulfate sprays (Bordeaux mixture)", "Pruning and burning infected wood"],
        "affected_season": "Summer (warm, wet conditions)",
    },
    "apple_cedar_rust": {
        "name": "Cedar Apple Rust",
        "crop": "Apple",
        "severity_default": "Moderate",
        "emoji": "🍎",
        "color": "#e67e22",
        "description": "Cedar apple rust is caused by Gymnosporangium juniperi-virginianae, a fungus that requires two different host plants (cedar/juniper and apple) to complete its life cycle.",
        "symptoms": ["Bright orange-yellow spots on upper leaf surface", "Pale greenish-yellow spots on leaf undersides", "Orange, cup-like structures on fruit"],
        "treatment": ["Apply preventative fungicide (myclobutanil, propiconazole) from tight cluster through petal fall", "Remove nearby cedar/juniper trees if possible"],
        "prevention": ["Plant rust-resistant apple varieties", "Remove nearby eastern red cedars", "Apply protective fungicides in spring"],
        "organic_treatment": ["Sulfur-based fungicides", "Copper sprays at bud break"],
        "affected_season": "Spring",
    },
    "apple_healthy": {
        "name": "Healthy Apple",
        "crop": "Apple",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your apple plant appears healthy! No disease symptoms detected. Continue with good agricultural practices to maintain plant health.",
        "symptoms": ["No disease symptoms detected", "Leaves are green and firm", "No spots, lesions or abnormal coloring"],
        "treatment": ["No treatment needed"],
        "prevention": ["Regular monitoring (scan weekly)", "Balanced NPK fertilization", "Proper irrigation management", "Annual pruning for air circulation"],
        "organic_treatment": ["Regular neem oil spray as preventative measure"],
        "affected_season": "All seasons",
    },
    "blueberry_healthy": {
        "name": "Healthy Blueberry",
        "crop": "Blueberry",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your blueberry plant appears healthy! Continue with good agricultural practices.",
        "symptoms": ["No disease symptoms", "Healthy green foliage"],
        "treatment": ["No treatment needed"],
        "prevention": ["Maintain soil pH between 4.5–5.5", "Regular mulching", "Adequate watering"],
        "organic_treatment": ["Preventative neem oil spray"],
        "affected_season": "All seasons",
    },
    "cherry_healthy": {
        "name": "Healthy Cherry",
        "crop": "Cherry",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your cherry plant appears healthy! No disease symptoms detected.",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Regular pruning", "Avoid overhead watering", "Monitor for pests"],
        "organic_treatment": ["Preventative copper spray before wet season"],
        "affected_season": "All seasons",
    },
    "cherry_powdery_mildew": {
        "name": "Cherry Powdery Mildew",
        "crop": "Cherry",
        "severity_default": "Moderate",
        "emoji": "🍒",
        "color": "#bdc3c7",
        "description": "Powdery mildew on cherry is caused by Podosphaera clandestina. It appears as a white powdery coating on young leaves and shoots.",
        "symptoms": ["White powdery coating on young leaves", "Distorted and stunted new growth", "Leaves curl upward", "Premature defoliation"],
        "treatment": ["Apply sulfur-based fungicide every 10 days", "Use potassium bicarbonate spray", "Prune out infected shoots"],
        "prevention": ["Plant in full sun with good air circulation", "Avoid excessive nitrogen fertilization", "Select resistant varieties"],
        "organic_treatment": ["Baking soda spray (1 tsp per liter)", "Neem oil spray", "Potassium bicarbonate"],
        "affected_season": "Late spring to summer",
    },
    "corn_gray_leaf_spot": {
        "name": "Corn Gray Leaf Spot",
        "crop": "Corn (Maize)",
        "severity_default": "Moderate",
        "emoji": "🌽",
        "color": "#7f8c8d",
        "description": "Gray leaf spot (GLS) is caused by the fungus Cercospora zeae-maydis. It is one of the most yield-limiting diseases of corn worldwide.",
        "symptoms": ["Rectangular, tan to gray lesions on leaves", "Lesions parallel to leaf veins", "Premature blighting of leaves", "Lesions may merge causing leaf death"],
        "treatment": ["Apply foliar fungicide (strobilurin or triazole) at tasseling stage", "Remove crop debris after harvest"],
        "prevention": ["Plant resistant hybrids", "Rotate corn with non-host crops (soybean, wheat)", "Till soil to reduce surface residue", "Avoid continuous corn planting"],
        "organic_treatment": ["Copper-based fungicide sprays", "Crop rotation is the most effective organic method"],
        "affected_season": "Mid to late season (warm, humid conditions)",
    },
    "corn_common_rust": {
        "name": "Corn Common Rust",
        "crop": "Corn (Maize)",
        "severity_default": "Moderate",
        "emoji": "🌽",
        "color": "#d35400",
        "description": "Common rust of corn is caused by Puccinia sorghi. While rarely causing major yield losses in field corn, it can be serious in sweet corn.",
        "symptoms": ["Small, circular to elongate, powdery pustules on leaf surfaces", "Pustules are cinnamon-brown colored", "Pustules occur on both upper and lower leaf surfaces", "Severe infection causes premature leaf death"],
        "treatment": ["Apply fungicide (triazole or strobilurin) if disease appears before silking", "Economic threshold: more than 50% of plants infected before silking"],
        "prevention": ["Plant resistant hybrids", "Early planting to avoid peak spore periods", "Monitor regularly"],
        "organic_treatment": ["Sulfur-based fungicides", "Neem oil sprays"],
        "affected_season": "Cool, moist conditions (often late summer/early fall)",
    },
    "corn_healthy": {
        "name": "Healthy Corn",
        "crop": "Corn (Maize)",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your corn plant appears healthy! Continue with good agronomic practices.",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Crop rotation", "Balanced fertilization", "Proper plant spacing"],
        "organic_treatment": ["Preventative monitoring"],
        "affected_season": "All seasons",
    },
    "corn_northern_leaf_blight": {
        "name": "Northern Corn Leaf Blight",
        "crop": "Corn (Maize)",
        "severity_default": "Severe",
        "emoji": "🌽",
        "color": "#e74c3c",
        "description": "Northern corn leaf blight (NCLB) is caused by Exserohilum turcicum. It is a major foliar disease that can cause significant yield losses.",
        "symptoms": ["Long, elliptical gray-green lesions (1–6 inches long)", "Lesions turn tan to brown as they age", "Lesions appear on lower leaves first", "Entire leaves may die in severe cases"],
        "treatment": ["Apply fungicide at VT (tasseling) stage if disease is detected", "Use strobilurin or triazole fungicides"],
        "prevention": ["Plant resistant or tolerant hybrids (most effective method)", "Crop rotation with non-corn crops", "Deep tillage to bury infected residue"],
        "organic_treatment": ["Crop rotation", "Copper-based fungicides"],
        "affected_season": "Mid to late season (cool, wet weather)",
    },
    "grape_black_rot": {
        "name": "Grape Black Rot",
        "crop": "Grape",
        "severity_default": "Severe",
        "emoji": "🍇",
        "color": "#8e44ad",
        "description": "Black rot is caused by the fungus Guignardia bidwellii. It is the most destructive disease of grapes in the eastern United States and can cause complete crop loss.",
        "symptoms": ["Reddish-brown circular leaf spots with dark borders", "Fruit shrivels and turns black ('mummies')", "Black pustules on infected tissue", "Cane lesions that appear reddish-brown"],
        "treatment": ["Apply fungicide (mancozeb, myclobutanil, captan) from bud break", "Remove all mummified fruit", "Prune to improve air circulation"],
        "prevention": ["Remove mummified fruit and infected canes during winter pruning", "Train vines to maximize air flow", "Apply preventive fungicide program from bud break"],
        "organic_treatment": ["Copper-based sprays", "Lime sulfur during dormancy"],
        "affected_season": "Spring through summer (warm, wet)",
    },
    "grape_black_measles": {
        "name": "Grape Black Measles (Esca)",
        "crop": "Grape",
        "severity_default": "Severe",
        "emoji": "🍇",
        "color": "#2c3e50",
        "description": "Black measles (also called Esca) is a complex disease caused by multiple wood-rotting fungi. It is one of the most economically damaging grapevine trunk diseases.",
        "symptoms": ["Tiger-stripe pattern of yellow and brown on leaves", "Small, dark berries with purple halos ('measles')", "Internal wood discoloration when canes are cut", "Sudden vine collapse (apoplexy) in severe cases"],
        "treatment": ["No effective chemical cure; remove severely affected vines", "Wound protectants after pruning", "Avoid pruning in wet conditions"],
        "prevention": ["Use clean pruning tools (disinfect between vines)", "Protect pruning wounds with wound sealant", "Avoid deep wounds", "Remove and destroy infected wood"],
        "organic_treatment": ["Trichoderma-based biological wound protectants", "Proper pruning hygiene"],
        "affected_season": "Summer (visible symptoms)",
    },
    "grape_leaf_blight": {
        "name": "Grape Leaf Blight",
        "crop": "Grape",
        "severity_default": "Moderate",
        "emoji": "🍇",
        "color": "#c0392b",
        "description": "Grape leaf blight (Isariopsis Leaf Spot) is caused by Pseudocercospora vitis. It causes premature defoliation and can affect fruit quality.",
        "symptoms": ["Irregular, dark brown spots on upper leaf surface", "Whitish mold growth on lower leaf surface", "Yellowing and premature leaf drop"],
        "treatment": ["Apply copper-based or broad-spectrum fungicide", "Improve air circulation through leaf removal"],
        "prevention": ["Avoid overhead irrigation", "Remove infected leaves promptly", "Thin canopy to improve air flow"],
        "organic_treatment": ["Copper hydroxide spray", "Bordeaux mixture"],
        "affected_season": "Mid to late summer",
    },
    "grape_healthy": {
        "name": "Healthy Grape",
        "crop": "Grape",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your grape vine appears healthy! Continue with good viticultural practices.",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Regular pruning", "Canopy management", "Preventive fungicide program"],
        "organic_treatment": ["Preventive sulfur spray during humid periods"],
        "affected_season": "All seasons",
    },
    "orange_citrus_greening": {
        "name": "Citrus Greening (HLB)",
        "crop": "Orange / Citrus",
        "severity_default": "Severe",
        "emoji": "🍊",
        "color": "#e67e22",
        "description": "Huanglongbing (HLB), also called Citrus Greening, is one of the most destructive citrus diseases. It is caused by bacteria transmitted by the Asian citrus psyllid insect.",
        "symptoms": ["Asymmetric (blotchy) mottling of leaves", "Yellow shoots ('yellow dragon' appearance)", "Small, lopsided, bitter fruit", "Fruit fails to color properly"],
        "treatment": ["No cure exists; remove and destroy infected trees", "Control psyllid vector with insecticides", "Use thermotherapy on mildly infected budwood"],
        "prevention": ["Use certified disease-free planting material", "Control psyllid populations aggressively", "Inspect trees regularly", "Quarantine affected areas"],
        "organic_treatment": ["Psyllid control through kaolin clay barrier sprays", "Introduction of natural psyllid predators"],
        "affected_season": "Year-round (symptoms worse in summer)",
    },
    "peach_bacterial_spot": {
        "name": "Peach Bacterial Spot",
        "crop": "Peach",
        "severity_default": "Moderate",
        "emoji": "🍑",
        "color": "#e74c3c",
        "description": "Bacterial spot, caused by Xanthomonas arboricola pv. pruni, is one of the most common and damaging diseases of peaches and nectarines.",
        "symptoms": ["Small, water-soaked spots on leaves that turn brown-purple", "Spots may drop out creating 'shot-hole' appearance", "Sunken, dark lesions on fruit", "Severe defoliation in wet years"],
        "treatment": ["Apply copper-based bactericide starting at petal fall", "Apply oxytetracycline (for bacterial control) during bloom", "Remove severely infected fruit"],
        "prevention": ["Plant resistant varieties", "Avoid overhead irrigation", "Prune to improve air circulation", "Avoid excessive nitrogen fertilization"],
        "organic_treatment": ["Copper hydroxide sprays", "Kaolin clay to reduce infection"],
        "affected_season": "Spring through summer",
    },
    "peach_healthy": {
        "name": "Healthy Peach",
        "crop": "Peach",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your peach tree appears healthy!",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Regular pruning", "Copper spray before bud break", "Monitor for pests"],
        "organic_treatment": ["Preventive copper spray"],
        "affected_season": "All seasons",
    },
    "pepper_bacterial_spot": {
        "name": "Pepper Bacterial Spot",
        "crop": "Bell Pepper",
        "severity_default": "Moderate",
        "emoji": "🫑",
        "color": "#e74c3c",
        "description": "Bacterial spot of pepper is caused by Xanthomonas euvesicatoria. It is a major disease of pepper in warm, humid climates.",
        "symptoms": ["Small, water-soaked spots that turn tan/brown with yellow halos", "Shot-hole appearance as centers drop out", "Dark, scabby lesions on fruit", "Defoliation in severe cases"],
        "treatment": ["Apply copper bactericide at first sign of disease", "Apply weekly during wet weather", "Remove infected plant material"],
        "prevention": ["Use disease-free seed or treated seed", "Practice 2–3 year crop rotation", "Avoid overhead irrigation", "Plant resistant varieties"],
        "organic_treatment": ["Copper hydroxide spray", "Avoid wetting foliage when watering"],
        "affected_season": "Summer (warm, wet conditions)",
    },
    "pepper_healthy": {
        "name": "Healthy Bell Pepper",
        "crop": "Bell Pepper",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your pepper plant appears healthy!",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Crop rotation", "Balanced fertilization", "Drip irrigation"],
        "organic_treatment": ["Preventive neem oil spray"],
        "affected_season": "All seasons",
    },
    "potato_early_blight": {
        "name": "Potato Early Blight",
        "crop": "Potato",
        "severity_default": "Moderate",
        "emoji": "🥔",
        "color": "#d35400",
        "description": "Early blight is caused by Alternaria solani. It is one of the most common foliage diseases of potato, especially in warm weather.",
        "symptoms": ["Dark brown to black spots with concentric rings (target-board pattern)", "Yellowing of tissue around spots", "Lower leaves affected first", "Spots may have yellow halo"],
        "treatment": ["Apply fungicide (chlorothalonil, mancozeb, azoxystrobin) at first sign", "Remove heavily infected lower leaves", "Apply every 7–10 days during wet periods"],
        "prevention": ["Rotate potato with non-solanaceous crops for 2–3 years", "Use certified disease-free seed pieces", "Avoid overhead irrigation", "Maintain plant health with adequate nutrition"],
        "organic_treatment": ["Copper-based fungicides", "Neem oil spray", "Baking soda solution"],
        "affected_season": "Warm, dry conditions followed by rain",
    },
    "potato_late_blight": {
        "name": "Potato Late Blight",
        "crop": "Potato",
        "severity_default": "Severe",
        "emoji": "🥔",
        "color": "#2c3e50",
        "description": "Late blight, caused by the oomycete Phytophthora infestans, is one of the most destructive plant diseases. It caused the Irish Potato Famine (1845–1849).",
        "symptoms": ["Large, dark brown, water-soaked lesions on leaves", "White fluffy mold on underside of leaves in humid conditions", "Black lesions on stems", "Infected tubers show reddish-brown rot"],
        "treatment": ["Apply fungicide (chlorothalonil, mancozeb, cymoxanil) immediately", "Protectant fungicides must be applied BEFORE infection", "Destroy infected plant material — do NOT compost"],
        "prevention": ["Plant certified disease-free seed potatoes", "Plant resistant varieties", "Rotate crops — do not plant potatoes/tomatoes in same field", "Monitor weather (high risk in cool, moist weather)"],
        "organic_treatment": ["Copper sulfate (Bordeaux mixture)", "Phosphonate sprays"],
        "affected_season": "Cool, wet conditions (15–20°C with high humidity)",
    },
    "potato_healthy": {
        "name": "Healthy Potato",
        "crop": "Potato",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your potato plant appears healthy!",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Crop rotation", "Certified seed potatoes", "Monitor weather forecasts"],
        "organic_treatment": ["Preventive copper spray in humid conditions"],
        "affected_season": "All seasons",
    },
    "raspberry_healthy": {
        "name": "Healthy Raspberry",
        "crop": "Raspberry",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your raspberry plant appears healthy!",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Prune old canes after harvest", "Weed control", "Good drainage"],
        "organic_treatment": ["Preventive neem oil"],
        "affected_season": "All seasons",
    },
    "soybean_healthy": {
        "name": "Healthy Soybean",
        "crop": "Soybean",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your soybean plant appears healthy!",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Crop rotation", "Resistant varieties", "Monitor for pests"],
        "organic_treatment": ["Preventive monitoring"],
        "affected_season": "All seasons",
    },
    "squash_powdery_mildew": {
        "name": "Squash Powdery Mildew",
        "crop": "Squash",
        "severity_default": "Moderate",
        "emoji": "🥬",
        "color": "#bdc3c7",
        "description": "Powdery mildew on squash and cucurbits is caused by Podosphaera xanthii or Erysiphe cichoracearum. It is the most common cucurbit disease.",
        "symptoms": ["White powdery spots on upper leaf surface", "Spots grow to cover entire leaf surface", "Affected leaves yellow and die", "Fruit may be exposed to sunscald"],
        "treatment": ["Apply fungicide (sulfur, potassium bicarbonate, myclobutanil)", "Begin treatment at first sign of disease", "Apply every 7–14 days"],
        "prevention": ["Plant resistant varieties", "Ensure good air circulation", "Avoid overhead watering", "Limit nitrogen fertilization"],
        "organic_treatment": ["Baking soda spray (1 tbsp per gallon)", "Neem oil", "Potassium bicarbonate", "Milk spray (40% milk / 60% water)"],
        "affected_season": "Late summer (warm, dry days + cool nights)",
    },
    "strawberry_leaf_scorch": {
        "name": "Strawberry Leaf Scorch",
        "crop": "Strawberry",
        "severity_default": "Moderate",
        "emoji": "🍓",
        "color": "#c0392b",
        "description": "Leaf scorch is caused by the fungus Diplocarpon earlianum. It is one of the most common and widespread diseases of strawberry.",
        "symptoms": ["Small, dark purple to reddish-purple spots on leaf surface", "Spots lack distinct borders (unlike leaf spot)", "Severely affected leaves look scorched and turn brown", "Petioles and stolons may also be affected"],
        "treatment": ["Apply fungicide (captan, myclobutanil) from green tip through petal fall", "Renovate planting after harvest by mowing and thinning"],
        "prevention": ["Plant resistant varieties", "Avoid overhead irrigation", "Renovate beds annually", "Space plants for air circulation"],
        "organic_treatment": ["Copper-based spray", "Remove infected leaves"],
        "affected_season": "Cool, wet spring weather",
    },
    "strawberry_healthy": {
        "name": "Healthy Strawberry",
        "crop": "Strawberry",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your strawberry plant appears healthy!",
        "symptoms": ["No disease symptoms"],
        "treatment": ["No treatment needed"],
        "prevention": ["Annual renovation", "Proper spacing", "Drip irrigation"],
        "organic_treatment": ["Preventive neem spray"],
        "affected_season": "All seasons",
    },
    "tomato_bacterial_spot": {
        "name": "Tomato Bacterial Spot",
        "crop": "Tomato",
        "severity_default": "Moderate",
        "emoji": "🍅",
        "color": "#e74c3c",
        "description": "Bacterial spot of tomato is caused by Xanthomonas species. It is a major disease in warm, humid climates and can devastate fruit quality.",
        "symptoms": ["Small, water-soaked spots that turn dark brown with yellow halos", "Shot-hole appearance on older leaves", "Raised, scabby lesions on green fruit", "Defoliation in severe cases"],
        "treatment": ["Apply copper bactericide at first sign", "Combine with mancozeb for better control", "Apply every 5–7 days during rainy periods"],
        "prevention": ["Use certified disease-free seed", "Drip irrigation — avoid wetting foliage", "Practice crop rotation (3+ years)", "Remove crop debris after harvest"],
        "organic_treatment": ["Copper hydroxide spray", "Avoid working in fields when plants are wet"],
        "affected_season": "Summer (warm, humid conditions)",
    },
    "tomato_early_blight": {
        "name": "Tomato Early Blight",
        "crop": "Tomato",
        "severity_default": "Moderate",
        "emoji": "🍅",
        "color": "#d35400",
        "description": "Early blight, caused by Alternaria solani, is one of the most common tomato diseases. Despite its name, it usually occurs mid-season when plants begin fruiting.",
        "symptoms": ["Dark brown spots with concentric rings (target-board pattern)", "Yellow halo around spots", "Lower leaves affected first", "Severely affected leaves turn yellow and drop"],
        "treatment": ["Apply fungicide (chlorothalonil, mancozeb, copper) at first symptom", "Continue every 7–10 days in wet weather", "Remove affected lower leaves"],
        "prevention": ["Stake or cage plants for air circulation", "Apply mulch to prevent soil splash", "Rotate crops — do not plant tomato in same spot for 3 years", "Water at base of plant"],
        "organic_treatment": ["Copper hydroxide spray", "Neem oil spray", "Baking soda solution"],
        "affected_season": "Mid-season (warm, wet with dew)",
    },
    "tomato_late_blight": {
        "name": "Tomato Late Blight",
        "crop": "Tomato",
        "severity_default": "Severe",
        "emoji": "🍅",
        "color": "#2c3e50",
        "description": "Late blight, caused by Phytophthora infestans, is a devastating disease that can destroy a tomato crop in days under the right conditions.",
        "symptoms": ["Large, greasy, gray-green lesions on leaves", "White mold on underside of lesions in humid conditions", "Brown, firm rot on fruit", "Stems develop dark brown lesions"],
        "treatment": ["Apply fungicide IMMEDIATELY — disease spreads very fast", "Use chlorothalonil, copper, or mancozeb", "Remove and bag infected plant parts — do NOT compost"],
        "prevention": ["Plant resistant varieties", "Avoid wet foliage (drip irrigation)", "Monitor weather — high risk at 15–20°C with humidity >90%", "Rotate crops"],
        "organic_treatment": ["Copper sulfate spray", "Remove infected plants immediately"],
        "affected_season": "Cool, wet weather (evening fog, dew)",
    },
    "tomato_leaf_mold": {
        "name": "Tomato Leaf Mold",
        "crop": "Tomato",
        "severity_default": "Moderate",
        "emoji": "🍅",
        "color": "#7f8c8d",
        "description": "Leaf mold is caused by the fungus Passalora fulva (formerly Fulvia fulva). It is a serious disease in humid greenhouse conditions.",
        "symptoms": ["Pale green to yellow spots on upper leaf surface", "Olive-green to gray mold on lower leaf surface", "Leaves may turn brown and wither", "Primarily affects leaves — fruit rarely infected"],
        "treatment": ["Apply fungicide (chlorothalonil, mancozeb, copper) at first sign", "Improve greenhouse ventilation", "Reduce relative humidity below 85%"],
        "prevention": ["Reduce humidity through ventilation", "Avoid wetting foliage", "Plant resistant varieties", "Space plants adequately"],
        "organic_treatment": ["Copper-based spray", "Potassium bicarbonate"],
        "affected_season": "High humidity conditions",
    },
    "tomato_septoria_leaf_spot": {
        "name": "Tomato Septoria Leaf Spot",
        "crop": "Tomato",
        "severity_default": "Moderate",
        "emoji": "🍅",
        "color": "#e67e22",
        "description": "Septoria leaf spot, caused by Septoria lycopersici, is one of the most common causes of early tomato defoliation.",
        "symptoms": ["Numerous small, circular spots (1/4 inch) with dark borders and gray-white centers", "Tiny black specks (pycnidia) visible in spot centers", "Lower leaves affected first", "Severe defoliation reduces yield and fruit quality"],
        "treatment": ["Apply fungicide (chlorothalonil, mancozeb, copper) when first symptoms appear", "Repeat every 7–10 days in wet weather", "Remove infected lower leaves"],
        "prevention": ["Rotate crops — avoid planting tomatoes in same spot for 3 years", "Mulch soil surface to prevent splash", "Water at base of plant — avoid overhead irrigation", "Remove plant debris at end of season"],
        "organic_treatment": ["Copper hydroxide spray", "Neem oil", "Remove and destroy infected leaves"],
        "affected_season": "When plants begin to set fruit (warm, wet weather)",
    },
    "tomato_spider_mites": {
        "name": "Tomato Spider Mites",
        "crop": "Tomato",
        "severity_default": "Moderate",
        "emoji": "🍅",
        "color": "#e74c3c",
        "description": "Two-spotted spider mites (Tetranychus urticae) are tiny arachnids, not fungi. They thrive in hot, dry conditions and can cause severe damage.",
        "symptoms": ["Tiny yellow or white speckles on upper leaf surface (stippling)", "Fine webbing on undersides of leaves", "Leaves turn bronze, yellow and drop", "Severe infestations stunt plant growth"],
        "treatment": ["Apply miticide (abamectin, bifenazate, or spiromesifen)", "Repeat in 5–7 days to catch newly hatched mites", "Avoid pyrethroid insecticides — they kill predatory mites"],
        "prevention": ["Maintain adequate soil moisture", "Avoid water stress — mites thrive in dry conditions", "Introduce predatory mites (Phytoseiulus persimilis)", "Avoid dusty conditions"],
        "organic_treatment": ["Insecticidal soap spray (spray undersides of leaves)", "Neem oil spray", "Water spray to dislodge mites", "Predatory mite releases"],
        "affected_season": "Hot, dry conditions",
    },
    "tomato_target_spot": {
        "name": "Tomato Target Spot",
        "crop": "Tomato",
        "severity_default": "Moderate",
        "emoji": "🍅",
        "color": "#8e44ad",
        "description": "Target spot is caused by Corynespora cassiicola. It affects leaves, stems, and fruit of tomato, particularly in warm, humid tropical and subtropical regions.",
        "symptoms": ["Brown spots with concentric rings and yellow halos on leaves", "Dark brown, sunken lesions on fruit", "Black lesions on stems and petioles", "Severe defoliation in humid conditions"],
        "treatment": ["Apply fungicide (azoxystrobin, chlorothalonil, mancozeb) at first sign", "Continue every 7–14 days"],
        "prevention": ["Improve air circulation through pruning", "Stake plants", "Avoid overhead irrigation", "Rotate crops"],
        "organic_treatment": ["Copper-based sprays", "Remove infected plant material"],
        "affected_season": "Warm, humid tropical conditions",
    },
    "tomato_mosaic_virus": {
        "name": "Tomato Mosaic Virus",
        "crop": "Tomato",
        "severity_default": "Severe",
        "emoji": "🍅",
        "color": "#f39c12",
        "description": "Tomato mosaic virus (ToMV) and tobacco mosaic virus (TMV) are highly stable plant viruses that can persist in soil and plant debris for years.",
        "symptoms": ["Mosaic pattern of light and dark green on leaves", "Leaf distortion — curling, puckering", "Fruit may show internal browning (necrosis)", "Stunted, yellow plants"],
        "treatment": ["No cure for virus-infected plants", "Remove and destroy infected plants", "Control aphid and whitefly vectors"],
        "prevention": ["Plant certified virus-free seed or transplants", "Plant resistant varieties (Tm gene)", "Control insect vectors (aphids, whiteflies)", "Wash hands and tools — virus spreads mechanically", "Do not smoke near plants — virus is present in tobacco"],
        "organic_treatment": ["Remove infected plants", "Control vectors with neem oil or insecticidal soap"],
        "affected_season": "All seasons (virus persists indefinitely)",
    },
    "tomato_yellow_leaf_curl": {
        "name": "Tomato Yellow Leaf Curl Virus",
        "crop": "Tomato",
        "severity_default": "Severe",
        "emoji": "🍅",
        "color": "#f1c40f",
        "description": "Tomato yellow leaf curl virus (TYLCV) is one of the most damaging tomato viruses worldwide, transmitted by whiteflies (Bemisia tabaci).",
        "symptoms": ["Upward curling of young leaves", "Yellowing of leaf margins and interveinal areas", "Stunted plant growth", "Flowers drop without setting fruit", "Plants infected early produce no yield"],
        "treatment": ["No cure; remove and destroy infected plants promptly", "Control whitefly populations aggressively with insecticide"],
        "prevention": ["Plant resistant varieties (TYLCV-resistant tomatoes)", "Control whitefly populations — primary vector", "Use reflective mulches to repel whiteflies", "Use row covers on young plants", "Remove weeds that host whiteflies"],
        "organic_treatment": ["Reflective silver mulch to repel whiteflies", "Yellow sticky traps to monitor whitefly", "Neem oil spray against whitefly nymphs", "Remove infected plants immediately"],
        "affected_season": "Summer and fall (peak whitefly season)",
    },
    "tomato_healthy": {
        "name": "Healthy Tomato",
        "crop": "Tomato",
        "severity_default": "Healthy",
        "emoji": "✅",
        "color": "#27ae60",
        "description": "Your tomato plant appears healthy! Excellent condition. Continue with regular care and monitoring.",
        "symptoms": ["No disease symptoms detected", "Leaves are green, firm and glossy", "No spots, lesions, or abnormal discoloration"],
        "treatment": ["No treatment needed"],
        "prevention": ["Water at base of plant to keep foliage dry", "Stake or cage for good air circulation", "Monitor weekly for early pest/disease detection", "Balanced fertilization (avoid excess nitrogen)"],
        "organic_treatment": ["Weekly preventive neem oil spray as insurance"],
        "affected_season": "All seasons",
    },
}

# Ordered list of all disease keys (for consistent indexing)
DISEASE_KEYS = list(DISEASES.keys())

def get_disease(key):
    """Get disease info by key. Returns healthy tomato if key not found."""
    return DISEASES.get(key, DISEASES["tomato_healthy"])

def get_severity_color(severity):
    colors = {
        "Healthy": "#27ae60",
        "Mild": "#f39c12",
        "Moderate": "#e67e22",
        "Severe": "#e74c3c"
    }
    return colors.get(severity, "#7f8c8d")

def get_severity_badge_class(severity):
    classes = {
        "Healthy": "badge-success",
        "Mild": "badge-warning",
        "Moderate": "badge-orange",
        "Severe": "badge-danger"
    }
    return classes.get(severity, "badge-secondary")
